### ISSUE TITLE
How can I open the front-end interface like a video presentation?

### ISSUE THREAD

**Issue by zcyzhu** [IBM/SecuringArt-using-Blockchain-DigitalCertificates#11]
How do I open the front-end interface, like the video display, open on localhost:4000 or use IBM cloud?

**Comment by asararatnakar** [comment]
@zcyzhu 

This is a code pattern, To demonstrate, how to store base64 encoded and encrypted images on a Blockchain ledger and retrieving the same. The application provided here doesn't cover front-end interface.

**Comment by zcyzhu** [comment]
@asararatnakar ，When I executed the `sudo ./bootstrap_app.sh` command, there was no problem. But when I executed `sudo ./quicktest.sh` I got an error.
```
POST instantiate chaincode on peer1 of Org1
POST invoke chaincode on peers of Org1

./quicktest.sh: line 151: /usr/bin/curl: Argument list too long


Image ID : 

GET query chaincode on peer1 of Org1
image data is compressed and saved as thumbnail in public/images directory

{
  "success": false,
  "message": "'args' field is missing or Invalid in the request"
}

```
The following error occurred in the `sudo ./bootstrap_app.sh` interface:
```
[2018-12-20 17:17:17.827] [ERROR] instantiate-chaincode - instantiate proposal was bad
[2018-12-20 17:17:17.828] [ERROR] instantiate-chaincode - instantiate proposal was bad
[2018-12-20 17:17:17.829] [DEBUG] instantiate-chaincode - Failed to send Proposal and receive all good ProposalResponse
[2018-12-20 17:17:17.829] [ERROR] instantiate-chaincode - Failed to instantiate. cause:Failed to send Proposal and receive all good ProposalResponse
(node:11109) UnhandledPromiseRejectionWarning: Error: Failed to instantiate. cause:Failed to send Proposal and receive all good ProposalResponse
    at Object.instantiateChaincode (/home/zcy/SecuringArt-using-Blockchain-DigitalCertificates/app/instantiate-chaincode.js:190:9)
    at <anonymous>
(node:11109) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)

```
When I execute the command `npm ls fabric-client fabric-ca-client`, my configuration is：
```

zcy@ubuntu:~/SecuringArt-using-Blockchain-DigitalCertificates$ npm ls fabric-client fabric-ca-client
balance-transfer@1.0.0 /home/zcy/SecuringArt-using-Blockchain-DigitalCertificates
├── fabric-ca-client@1.3.0 
└── UNMET DEPENDENCY fabric-client@^1.2.0

npm ERR! missing: fabric-client@^1.2.0, required by balance-transfer@1.0.0

```
Where is the problem? How can I achieve the desired result?

**Comment by zcyzhu** [comment]
When I executed sudo ./bootstrap_app.sh, there was no error, but I did not get an error when I executed./quicktest.shon another terminal, but no result was returned.
My fabric-ca-client and fabric-client versions are 1.2.0,The grpc version is 1.10.1
No results at all.   No errors occurred, just the data could not be obtained
POST invoke chaincode on peers of Org1 ./quicktest.sh: line 151: /usr/bin/curl: Argument list too long Image ID :  GET query chaincode on peer1 of Org1 image data is compressed and saved as thumbnail in public/images directory {   "success": false,   "message": "'args' field is missing or Invalid in the request" }




------------------ 原始邮件 ------------------
发件人: "Ratnakar"<notifications@github.com>;
发送时间: 2018年12月19日(星期三) 晚上9:05
收件人: "IBM/SecuringArt-using-Blockchain-DigitalCertificates"<SecuringArt-using-Blockchain-DigitalCertificates@noreply.github.com>;
抄送: "清飘随风"<249816272@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IBM/SecuringArt-using-Blockchain-DigitalCertificates] How can Iopen the front-end interface like a video presentation? (#11)




@zcyzhu
 
This is a code pattern, To demonstrate, how to store base64 encoded and encrypted images on a Blockchain ledger and retrieving the same. The application provided here doesn't cover front-end interface.

**Comment by asararatnakar** [comment]
@zcyzhu Could you try as suggested here https://unix.stackexchange.com/a/174355
