### ISSUE TITLE
Error during execution of quicktest.sh script.

### ISSUE THREAD

**Issue by grabastart** [IBM/SecuringArt-using-Blockchain-DigitalCertificates#7]
Env:
Ubunto 18.04 on VM

Failed to create channel, thus, the script stopped there.

The following is from the app server terminal screen:
[2018-09-23 12:09:29.727] [DEBUG] Helper - [crypto_ecdsa_aes]: ecdsa signature:  Signature {
  r: <BN: e75ba234aec2b9b68fa8c1077ed0d77a556b6238b3d3be5c18bed14798a96875>,
  s: <BN: 33779b95df36e2d61aa3f16a17807211fbfae74eb5a41108e4ba4b40550fa602>,
  recoveryParam: 1 }
node: symbol lookup error: /home/donli/SecuringArt-using-Blockchain-DigitalCertificates/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node: undefined symbol: SSL_library_init

How can I help to debug?

**Comment by asararatnakar** [comment]
@grabastart  How did you installed the node.js version on your Ubuntu ? 
Is your version of node installed via **nvm** or **apt** ?
There are some issues with Ubuntu repo node.js version

**Comment by zcyzhu** [comment]
@asararatnakar,How can I open the front-end interface like a video presentation?How do I open the front-end interface, like the video display, open on localhost:4000 or use IBM cloud?
